# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZTPtEXMihI__yOGQB85hwEyZkjc50D7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

files.upload()

df = pd.read_csv("^NSEBANK.csv")
df = df.set_index(pd.to_datetime(df['Date']))
df

plt.figure(figsize=(16,8))
plt.title('close price history', fontsize=18)
plt.plot(df['Close'])
plt.xlabel('Date',fontsize=18)
plt.ylabel('close prize',fontsize=18)

def SMA(data,period =50, col="Close"):
  return data[col].rolling(window=period).mean()

df['SMA50']=SMA(df,50)
df['SMA100']=SMA(df,100)

df['signal']=np.where(df['SMA50']>df['SMA100'],1,0)
df['position']=df['signal'].diff()
df['Buy']=np.where(df['position']==1, df['Close'], np.NAN)
df['Sell']=np.where(df['position']==-1,df['Close'],np.NAN)

plt.figure(figsize=(16,8))
plt.title('Buy and Sell', fontsize=18)
plt.plot(df['Close'],alpha=0.5,label='Close')
plt.plot(df['SMA50'],alpha=0.5,label='SMA50')
plt.plot(df['SMA100'],alpha=0.5,label='SMA100')
plt.scatter(df.index,df['Buy'],alpha=1,label='Buy signal',marker='^',color='green')
plt.scatter(df.index,df['Sell'],alpha=1,label='Sell signal',marker='v',color='red')
plt.xlabel('Date',fontsize=18)
plt.ylabel('close prize',fontsize=18)
plt.show()